---
title: The Undefeatable Budget Constraint
author: Simon Naitram
date: '2018-10-24'
slug: the-undefeatable-budget-constraint
type: "post"
description: You just can't beat it.
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(ggplot2)
library(reshape2)
library(directlabels)
library(ggtech)
library(dplyr)
library(waffle)
```

Imagine a Barbados that has no government. Imagine a Barbados that has never had a government. Now imagine that today, we elected our very first prime minister---**you**. Your job is now to build a government from scratch. You decide what we need, and how to finance it.

Take a few minutes to think.

Re-imagine Barbados. How would you design it? What would the government actually need to do? Be original. Think only of exactly what the country *needs*, not what it currently has.

How would you raise money? Would you ask for donations? Would you ask those who use your services to pay for them? Would you force people to make a donation? Would you ask companies to help out?

There is only one constraint. **The Budget Constraint**. You must respect the budget constraint. What is the budget constraint? Simple. You cannot spend more than you earn. Every extra dollar you want to spend must be extracted from the people. Every dollar must be carefully considered.

Think, more deeply, about what you want this country to look like in 10 years. Think about what a government would *need* to do to faciliate that vision. Do you envisage a Barbados that looks pretty much as it looks today? How disappointing that would be.


