---
title: Democratising Business
author: Simon Naitram
date: '2019-05-16'
slug: democratising-business
categories: []
tags: []
draft: true
---

You have a *great* business idea. You have a *great* business plan. You have the skills to execute. You are the *ideal* entrepreneur.

There's only one thing missing---the money to start your business. In Barbados, where do you get that money? 

I'll hazard a quick guess---you don't. Unless, of course, your family is rich. Or maybe you're friends with rich people. Or you work for three decades to save up enough money to start your business. Or you sell your house in order to start your business.

Business ownership is not open to everyone. It is not an option available to all of Barbados. 

A government grant of \$5,000 is cute. But apart from a lemonade stand, what business can you start with \$5,000?

Let's talk about your favourite companies. Did they really just start in someone's garage? Nope. Apple, Amazon, Microsoft. Their rags to riches stories are all fairy tales. 

Barbados is 215th out of 233 countries on the employer to employment ratio. That is we have one employer for every 111 employees The rest of the world has 1 employer for every 33 employees.

We barely have any businesses. That's because only a select few can start businesses---those who already have money. 

Let's not pretend that Barbados provides equal opportunities for everyone. 
